### ISSUE TITLE
Disabling raise_job_errors with a single action call results in IndexError

### ISSUE THREAD

**Issue by dcartereb** [eventbrite/pysoa#152]
When using `raise_job_errors=False`, I instead received `IndexError: list index out of range`.  It appears that the client is trying to reference `actions[0]` in `call_action_future`, but since there is only one call that had a JobError, there is no action to reference.
```
Traceback (most recent call last):
  File "/usr/local/www/REDACTED/lib/python2.7/site-packages/service/job.py", line 867, in run
    action.run(self, controller, idx)
  -- STACK TRACE REDACTED
  File "/usr/local/www/REDACTED/lib/python2.7/site-packages/REDACTED/utils.py", line 121, in get_hierarchy_from_coordinates
    raise_job_errors=False,
  File "/usr/local/www/REDACTED/lib/python2.7/site-packages/pysoa/client/client.py", line 390, in call_action
    return self.call_action_future(service_name, action, body, **kwargs).result()
  File "/usr/local/www/REDACTED/lib/python2.7/site-packages/pysoa/client/client.py", line 245, in result
    self._response = self._get_response(timeout)
  File "/usr/local/www/REDACTED/lib/python2.7/site-packages/pysoa/client/client.py", line 594, in <lambda>
    return self.FutureResponse(lambda _timeout: future.result(_timeout).actions[0])
IndexError: list index out of range
```

**Comment by nickwilliams-eventbrite** [comment]
Fixed in #157.
