### ISSUE TITLE
"IndexError: list index out of range" in Client. _expand_objects

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [eventbrite/pysoa#156]
Unknown cause at this point.

```
Traceback (most recent call last):
...
  File "pysoa/client/client.py", line 450, in call_actions
    **kwargs
  File "pysoa/client/client.py", line 245, in result
    self._response = self._get_response(timeout)
  File "pysoa/client/client.py", line 653, in get_response
    self._perform_expansion(response.actions, expansions, **kwargs)
  File "pysoa/client/client.py", line 889, in _perform_expansion
    self._expand_objects(objects_to_expand, **kwargs)
  File "pysoa/client/client.py", line 964, in _expand_objects
    action_response = response.actions[0]
IndexError: list index out of range
```

**Comment by nickwilliams-eventbrite** [comment]
Fixed in #157.
